### ISSUE TITLE
Compilation with g++ doesn't work on fedora 39

### ISSUE THREAD

**Issue by Bombylius** [varqox/sip#4]
When sip tries to compile a solution g++ gives an error:
```
g++: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
```
After copying `cc1plus` from `/usr/libexec/gcc/x86_64-redhat-linux/13/` to `/usr/bin` I got:
```
g++: fatal error: '-fuse-linker-plugin', but liblto_plugin.so not found
```
`liblto_plugin.so` is also in `/usr/libexec/gcc/x86_64-redhat-linux/13/`.
When I ran sip with strace I saw that g++ does try to access these files but for some reason it can't find them:
```
241706 access("/usr/libexec/gcc/x86_64-redhat-linux/13/liblto_plugin.so", R_OK) = -1 ENOENT (No such file or directory)
```

**Comment by varqox** [comment]
What distribution and which version are you using?

**Comment by Bombylius** [comment]
Fedora 39, as mentioned in the title.

**Comment by varqox** [comment]
Ah, sorry, I didn't notice :)

**Comment by varqox** [comment]
Please check if it works now and give me feedback.

**Comment by Bombylius** [comment]
Everything seems to work now and all tests pass :)
