### ISSUE TITLE
Test `sandbox_uses_user_namespace` fails on Arch

### ISSUE THREAD

**Issue by m4l352k4** [varqox/sip#5]
Cannot build AUR package as `sandbox/sandbox_uses_user_namespace` test fails. Logs:

```
../sip/subprojects/simlib/test/sandbox/sandbox_uses_user_namespace.cc:23: Failure
Expected equality of these values:
  _assert_result_ok_si
    Which is: 8-byte object <03-00 00-00 06-00 00-00>
  (::sandbox::Si{.code = _si_code, .status = (0)})
    Which is: 8-byte object <01-00 00-00 00-00 00-00>
killed and dumped by signal ABRT - Aborted
```

Latest commit working on Arch is b4614de916dfecf834b10e817663e69c57669e00.

**Comment by varqox** [comment]
You are having issues with the new sandbox (the last working commit is the last commit using the old sandbox). Also what kernel are you running and what modifications of the kernel are you using?

First of all, can you post the full log of the failing test including stderr?
Should look something like this:
```
>>> MALLOC_PERTURB_=100 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 LD_LIBRARY_PATH=/home/quasar/src/sip/build/subprojects/simlib ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 /home/quasar/src/sip/build/subprojects/simlib/test_sandbox_sandbox_uses_user_namespace_cc /home/quasar/src/sip/build/subprojects/simlib/test_sandbox_sandbox_uses_user_namespace_tester_cc
―――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from sandbox
[ RUN      ] sandbox.test_uids_and_gids
../subprojects/simlib/test/sandbox/sandbox_uses_user_namespace.cc:29: Failure
Expected equality of these values:
  _assert_result_ok_si
    Which is: 8-byte object <02-00 00-00 06-00 00-00>
  (::sandbox::Si{.code = _si_code, .status = (0)})
    Which is: 8-byte object <01-00 00-00 00-00 00-00>
killed by signal ABRT - Aborted

../subprojects/simlib/test/sandbox/sandbox_uses_user_namespace.cc:29: Failure
Failed

[  FAILED  ] sandbox.test_uids_and_gids (82 ms)
[----------] 1 test from sandbox (82 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (82 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] sandbox.test_uids_and_gids

 1 FAILED TEST
stderr:
terminate called after throwing an instance of 'std::runtime_error'
  what():  ../subprojects/simlib/test/sandbox/sandbox_uses_user_namespace_tester.cc:15: int main(int, char **): Assertion `getuid() == expected_uid - 1` failed.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by m4l352k4** [comment]
Oh, yes, I haven't noticed the stderr output section.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ../sip/subprojects/simlib/test/sandbox/sandbox_uses_user_namespace_tester.cc:16: int main(int, char**): Assertion `getgid() == expected_gid` failed.
```

I've tried building dev build of simlib and running the test under GDB but the only thing I've come to is that the supervisor actually thinks that the process in it has a different gid than the process itself --- so actually not much more than stderr says. 

I'm running linux-lts kernel version 6.6.16-1-lts without any additional patches. I see now it's a little bit outdated. I will let you know if this problem still occurs after updating to 6.6.18-1-lts.

Edit: nothing's changed after upgrading to 6.6.18-1-lts.

**Comment by varqox** [comment]
Could you try the current main branch?
If it fails please post me the test output errors with stderr.

**Comment by m4l352k4** [comment]
Sure.

```
expected_uid: 1000
expected_gid: 1001
ruid: 1000 euid: 1000 suid: 1000
rgid: 1000 egid: 1000 sgid: 1000
terminate called after throwing an instance of 'std::runtime_error'
  what():  ../test/sandbox/sandbox_uses_user_namespace_tester.cc:34: int main(int, char**): Assertion `rgid == expected_gid` failed.
```

On my installation, each user belongs to its own group and GID 1001 is the group that my user belongs to. GID 1000 is for sudo.

As far as I understand it, the tester process is executed inside `/usr/bin/systemd-run` --- maybe that causes the GID mismatch?

**Comment by m4l352k4** [comment]
On default arch installation, each user belongs to a separate group. Here, 1001 is the group that my account belongs to and 1000 is the sudo group.

**Comment by varqox** [comment]
Okey, I'm finally able to reproduce the issue locally.
Working on a fix now.

**Comment by varqox** [comment]
Okey, should work now, can you check?

**Comment by m4l352k4** [comment]
Everything works now :+1:
